Added marketplace listing non-citizen upcharge
Official-MoonDao/MoonDAO pull request #244
Opened 2024-11-08 00:03 UTC by namedotget

- Marketplace listings cost 10% more for non-citizens

2024-11-08 01:38 UTC, pmoncada requested changes
Two things here...

1.) We need to communicate when people are listing that non-citizens will get charged 10% more.
2.) Please add a test to demonstrate the new feature!

2024-11-08 17:21 UTC, namedotget commented
> Two things here...
> 
> 1.) We need to communicate when people are listing that non-citizens will get charged 10% more. 2.) Please add a test to demonstrate the new feature!

In the 2nd commit of this PR I added a message to the TeamMarketplaceListingModal

2024-11-08 19:13 UTC, pmoncada requested changes

2024-11-08 19:13 UTC, pmoncada commented on ui/lib/subscription/getMarketplaceListings.ts
> +import { Arbitrum, Sepolia } from '@thirdweb-dev/chains'
Nice! Could you also add a test for the expiration? Add a listing w/ an expiration and make sure that it renders as expired.

2024-11-08 19:13 UTC, pmoncada commented on ui/cypress/e2e/marketplace.cy.ts
> +import getMarketplaceListings from '@/lib/subscription/getMarketplaceListings'
Could we also test the inverse? E.g. a signed in Citizen should see this without the upcharge

2024-11-08 19:21 UTC, namedotget commented on ui/lib/subscription/getMarketplaceListings.ts
> +import { Arbitrum, Sepolia } from '@thirdweb-dev/chains'
I will add that in the next PR, haven't pushed marketplace/job expirations yet

2024-11-11 17:58 UTC, pmoncada approved these changes
Nice! Awesome that the privy provider is working

2024-11-11 18:17 UTC, merged